import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-terms',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="static-page">
      <header class="page-header">
        <div class="header-inner">
          <a routerLink="/login" class="back-link">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M10 3L5 8l5 5"/>
            </svg>
            Back
          </a>
          <span class="org-label">ENTERPRISE TEMPLATE</span>
        </div>
      </header>

      <main class="page-main">
        <div class="content-card">
          <h1>Terms of Service</h1>
          <p class="effective-date">Effective date: 1 January 2026</p>

          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              Welcome to the Enterprise Platform ("the Platform"). By accessing or using the Platform,
              you agree to these Terms of Service. If you do not accept these terms, please do not use the Platform.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              The Platform provides business consulting and management services for organisations enrolled in
              the programme. Services are intended exclusively for authorised participants.
            </p>
            <p><strong>Taking part in the programme is free of charge.</strong></p>
          </section>

          <section>
            <h2>3. Eligibility and Registration</h2>
            <p>
              Access is limited to organisations formally enrolled in the programme.
              Each account is associated with a specific organisation; login credentials must not
              be shared with third parties.
            </p>
          </section>

          <section>
            <h2>4. Acceptable Use</h2>
            <p>As a Platform user, you agree to:</p>
            <ul>
              <li>provide accurate and up-to-date information about your organisation;</li>
              <li>use the Platform for lawful purposes only;</li>
              <li>not attempt to circumvent security measures;</li>
              <li>not distribute Platform outputs as official advice;</li>
              <li>not use the Platform to generate misleading or fraudulent content.</li>
            </ul>
          </section>

          <section>
            <h2>5. Artificial Intelligence and Accuracy</h2>
            <p>
              Recommendations generated by the Platform are AI-based and provided for informational purposes only.
              They do not constitute legal, financial, or regulatory advice.
              Users should consult qualified professionals before making significant decisions.
            </p>
          </section>

          <section>
            <h2>6. Data Privacy</h2>
            <p>
              Processing of personal data is governed by our
              <a routerLink="/privacy">Privacy Policy</a> and the consent conditions
              you accepted during registration. The Platform complies with applicable data protection law.
            </p>
          </section>

          <section>
            <h2>7. Intellectual Property</h2>
            <p>
              All content, functionality, and technology of the Platform are owned by or licensed to Example Org.
              Users receive a limited, non-transferable licence to use the Platform solely for the purposes
              of the programme.
            </p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              The Platform is provided "as is". Example Org makes no warranties regarding the continuity or
              error-free operation of the service. To the maximum extent permitted by applicable law,
              Example Org shall not be liable for any damages arising from use of the Platform.
            </p>
          </section>

          <section>
            <h2>9. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms. For material changes, users will be notified
              through the Platform. Continued use after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2>10. Contact</h2>
            <p>
              For enquiries, contact us at
              <a href="mailto:support@example.org">support&#64;example.org</a>.
            </p>
          </section>
        </div>
      </main>

      <footer class="page-footer">
        <span>© 2026 Example Org</span>
        <span class="divider">·</span>
        <a routerLink="/privacy">Privacy</a>
        <span class="divider">·</span>
        <a routerLink="/terms">Terms</a>
      </footer>
    </div>
  `,
  styles: [`
    .static-page {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      background: var(--color-neutral-50);
      font-family: system-ui, -apple-system, sans-serif;
    }
    .page-header {
      background: var(--color-primary);
      color: white;
      padding: 0 2rem;
    }
    .header-inner {
      max-width: 800px;
      margin: 0 auto;
      height: 56px;
      display: flex;
      align-items: center;
      gap: 1rem;
    }
    .back-link {
      display: flex;
      align-items: center;
      gap: 0.375rem;
      color: rgba(255,255,255,0.85);
      text-decoration: none;
      font-size: var(--font-size-sm);
      transition: color 0.15s;
    }
    .back-link:hover { color: white; }
    .org-label {
      font-size: var(--font-size-xs);
      font-weight: 500;
      letter-spacing: 0.06em;
      color: rgba(255,255,255,0.7);
      flex: 1;
      text-align: center;
    }
    .page-main { flex: 1; padding: 2.5rem 1.5rem; }
    .content-card {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      border-radius: var(--radius-card);
      border: 1px solid var(--color-border);
      padding: 2.5rem 3rem;
    }
    h1 { font-size: var(--font-size-2xl); font-weight: 700; color: var(--color-primary); margin: 0 0 0.5rem; }
    .effective-date { font-size: var(--font-size-sm); color: var(--color-text-secondary); margin: 0 0 2rem; }
    section { margin-bottom: 2rem; }
    h2 {
      font-size: var(--font-size-lg); font-weight: 600; color: var(--color-primary);
      margin: 0 0 0.625rem; padding-bottom: 0.375rem; border-bottom: 1px solid var(--color-neutral-100);
    }
    p { font-size: var(--font-size-md); line-height: 1.7; color: var(--color-gray-700); margin: 0 0 0.75rem; }
    ul { margin: 0.5rem 0 0.75rem 1.25rem; padding: 0; }
    li { font-size: var(--font-size-md); line-height: 1.7; color: var(--color-gray-700); margin-bottom: 0.25rem; }
    a { color: var(--color-info-hover); text-decoration: underline; text-underline-offset: 2px; }
    a:hover { color: var(--color-primary); }
    .page-footer {
      background: white; border-top: 1px solid var(--color-border);
      padding: 1rem 2rem; display: flex; justify-content: center;
      align-items: center; gap: 0.75rem; font-size: var(--font-size-xs); color: var(--color-text-secondary);
    }
    .page-footer a { color: var(--color-text-secondary); text-decoration: none; }
    .page-footer a:hover { color: var(--color-primary); }
    .divider { color: var(--color-border); }
    @media (max-width: 640px) { .content-card { padding: 1.5rem; } h1 { font-size: var(--font-size-xl); } }
  `]
})
export class TermsComponent {}
